### ISSUE TITLE
about SK-LARGE/list.txt

### ISSUE THREAD

**Issue by husencd** [zeakey/skeleton#2]
Update: Sorry, I have found the txt file. It's the _train_pair.lst_ in the _aug_data folder_.
---

Hello! I met an error as follows:

I0722 22:13:27.846886 30175 layer_factory.hpp:76] Creating layer data
I0722 22:13:27.846915 30175 net.cpp:111] Creating Layer data
I0722 22:13:27.846926 30175 net.cpp:434] data -> data
I0722 22:13:27.846951 30175 net.cpp:434] data -> label
I0722 22:13:27.846973 30175 image_labelmap_data_layer.cpp:40] Opening file data/SK-LARGE/list.txt
I0722 22:13:27.846997 30175 image_labelmap_data_layer.cpp:50] Shuffling data
I0722 22:13:27.847069 30175 image_labelmap_data_layer.cpp:55] A total of 0 images.
Segmentation fault (core dumped)

Is something missed in SK-LARGE folder? I don't find file data/SK-LARGE/list.txt. Thx!

**Comment by zeakey** [comment]
Did you do **data augmentation** as suggested in <http://kaiz.xyz>?
If you didn't, follow the steps there to do data augmentation first.

**Comment by hustcc19860606** [comment]
I have the same problem. Is data/SK-LARGE/list.txt one temporal  file? Is it produced by data augmentation? I have done data augmentation as suggested in http://kaiz.xyz/sk-large.

**Comment by KunWang123** [comment]
I also have met this question, after data augmentation.
