### ISSUE TITLE
Question about running training.py

### ISSUE THREAD

**Issue by yeLer** [zeakey/skeleton#3]
I have done the data agumentation by the tips of your website ,and I get the result like this.
![image](https://user-images.githubusercontent.com/16631986/46600946-5af0fb80-cb1e-11e8-9888-a1277e81a98e.png)
In this folder,i can't find a txt file named list.txt.So when I run the training.py,I meet the problem like this.

I1008 16:43:02.081221 25387 net.cpp:76] Memory required for data: 0
I1008 16:43:02.081353 25387 layer_factory.hpp:76] Creating layer data
I1008 16:43:02.081411 25387 net.cpp:111] Creating Layer data
I1008 16:43:02.081424 25387 net.cpp:434] data -> data
I1008 16:43:02.081471 25387 net.cpp:434] data -> label
I1008 16:43:02.081509 25387 image_labelmap_data_layer.cpp:40] Opening file data/SK-LARGE/list.txt
I1008 16:43:02.081531 25387 image_labelmap_data_layer.cpp:50] Shuffling data
I1008 16:43:02.081581 25387 image_labelmap_data_layer.cpp:55] A total of 0 images.
Segmentation fault (core dumped)

I find the train prtotxt file fsds_train.prototxt,the source is  "data/SK-LARGE/list.txt".
![image](https://user-images.githubusercontent.com/16631986/46601245-1f0a6600-cb1f-11e8-82a7-32726e2be898.png)
I think the problem is missing this txt file,could you add the txt file in this repo, or give me some suggestion about  list.txt file.Thank you very much!

**Comment by zeakey** [comment]
As shown in <https://github.com/SHUCV/SK-LARGE/blob/master/augmentation.m#L17>， `train_pair.lst` 
is the txt you are looking for.

**Comment by yeLer** [comment]
I get it,Thank you again!
